language: rust
# sudo is required to enable kcov to use the personality syscall
sudo: required

before_install:
  - git clone https://github.com/eldruin/rust-driver-ci-scripts ci
  - bash ci/before_install.sh

matrix:
  fast_finish: true
  allow_failures:
      - rust: nightly
  include:
      - rust: stable
      env: NAME='linting'
      before_script:
        - export PATH=$HOME/.cargo/bin:$PATH
        - rustup component add rustfmt-preview
        - rustup component add clippy-preview
      script:
        - cargo fmt --all -- --check
        - cargo clippy

    - env: TARGET=x86_64-unknown-linux-gnu
      before_script:
        - bash ci/coverage_before_script.sh
      after_success:
        - bash ci/coverage_after_success.sh
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - cmake
          sources:
            - kalakris-cmake

    - env: TARGET=x86_64-unknown-linux-gnu
      rust: 
        - stable
        - beta
        - nightly

install:
  bash ci/install.sh

script:
  bash ci/script.sh

after_script: set +e

cache: cargo
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  bash ci/before_cache.sh

notifications:
  email:
    on_success: never
